.\" $Id$

.\" catcodec is a tool to decode/encode the sample catalogue for OpenTTD.
.\" Copyright (C) 2009  Remko Bijker
.\"
.\" This manual page is free software.  It is distributed under the
.\" terms of the GNU General Public License as published by the Free
.\" Software Foundation; either version 2 of the License.
.\"
.\" This manual page is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this manual page; if not, write to the Free Software
.\" Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
.\" USA
.\"
.Dd November 05, 2009
.Dt CATCODEC 1
.Sh NAME
.Nm catcodec
.Nd An open source tool to decode/encode the sample catalogue for OpenTTD
.Sh SYNOPSIS
.Nm
.Op Fl d Ar sample_file
.Op Fl e Ar sample_file
.Sh DESCRIPTION
catcodec decodes and encodes sample catalogues for OpenTTD. These sample
catalogues are not much more than some meta-data (description and file name)
and raw PCM data.
.sp
Decoding a sample catalogue, e.g. sample.cat, results in a sample.sfo that
contains the file names and descriptions of the samples and all samples with
the file name as specified in the catalogue.
.sp
Encoding a sample catalogue, e.g. sample.cat, reads sample.sfo for the file
names and descriptions. It will then load the samples described in sample.sfo
and encodes these into sample.cat.
.sp
Generally speaking encoding a file and then decoding it results in the same
file. Decoding of the original, Transport Tycoon Deluxe, sample format will
force the output to be 11025 Hz, 8 bits mono because the meta-data of some
of the samples is incorrect or even missing.
.sp
Only PCM WAVE files with only the format and data chunks are supported. Any
other formats need to be converted into this. Furthermore only 11025 Hz,
22050 Hz and 44100 Hz with 8 or 16 bits per sample single channel PCM WAVE
files are supported.
.sp
.Sh OPTIONS
.Bl -tag -width ".Fl d Ar sample_file"
.It Fl d Ar sample_file
Decode the given sample catalogue into its components. The
.Ar sample_file
must have the extension '.cat'. For the output meta-data file the '.cat' is
replaced with '.sfo'. The actual samples, in PCM WAVE format, are extracted
into files using the file names, including extension, as described in the
catalogue or meta-data file.
.sp
If any of the files already exists a backup is made, by adding '.bak',
overwriting the existing backup.
.sp
.It Fl e Ar sample_file
Encode the components for the given sample file into a sample catalogue. The
.Ar sample_file
must have the extension '.cat'. For the input meta-data file the '.cat' is
replaced with '.sfo'. The actual samples, in PCM WAVE format, are read from
files using the file names, including extension, as described in the
meta-data file.
.sp
If the
.Ar sample_file
already exists a backup is made, by adding '.bak', overwriting the existing
backup.
.sp
.El
.Sh SEE ALSO
.Nm openttd Ns (1)
the game that uses these sample catalogues.
.sp
.Sh AUTHORS
.An Remko Bijker
.Aq rubidium@openttd.org
