name: CI

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  build:
    name: Build

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
         - os: windows-latest
           makefile: Makefile.msvc
         - os: ubuntu-latest
           makefile: Makefile

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set build environment
      if: matrix.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86
    - name: Build
      run: make -f ${{ matrix.makefile }}
      shell: bash
